// e-ticaretv6/onlyfrontend/components/footer.tsx
import Link from "next/link"
import { Facebook, Twitter, Instagram, Linkedin, Mail, Phone } from "lucide-react"

export default function Footer() {
  return (
    <footer className="border-t">
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-lg font-semibold mb-4">3D Print Hub</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Your one-stop solution for all 3D printing needs. Quality products and services for professionals and
              hobbyists.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-4">Quick Links</h3>
            <ul className="space-y-2">
              <li>
                <Link href="/about" className="text-sm hover:underline">
                  About Us
                </Link>
              </li>
              <li>
                <Link href="/services" className="text-sm hover:underline">
                  Services
                </Link>
              </li>
              <li>
                <Link href="/faq" className="text-sm hover:underline">
                  FAQ
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-sm hover:underline">
                  Contact Us
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-4">Contact Information</h3>
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm">
                <Mail className="h-4 w-4" />
                <span>info@3dprinthub.com</span>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <Phone className="h-4 w-4" />
                <span>+1 (555) 123-4567</span>
              </div>
            </div>

            <div className="mt-4">
              <h4 className="text-sm font-medium mb-2">Follow Us</h4>
              <div className="flex space-x-4">
                <Link href="https://twitter.com" className="hover:text-primary">
                  <Twitter className="h-5 w-5" />
                  <span className="sr-only">Twitter</span>
                </Link>
                <Link href="https://facebook.com" className="hover:text-primary">
                  <Facebook className="h-5 w-5" />
                  <span className="sr-only">Facebook</span>
                </Link>
                <Link href="https://instagram.com" className="hover:text-primary">
                  <Instagram className="h-5 w-5" />
                  <span className="sr-only">Instagram</span>
                </Link>
                <Link href="https://linkedin.com" className="hover:text-primary">
                  <Linkedin className="h-5 w-5" />
                  <span className="sr-only">LinkedIn</span>
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 pt-4 border-t text-center">
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} 3D Print Hub. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  )
}

// e-ticaretv6/frontend/src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-top">
      <div class="social-icons">
        <a href="https://twitter.com" target="_blank">Twitter</a>
        <a href="https://facebook.com" target="_blank">Facebook</a>
        <a href="https://instagram.com" target="_blank">Instagram</a>
        <a href="https://linkedin.com" target="_blank">LinkedIn</a>
      </div>
      <div class="contact-info">
        <p>Email: support@3dprintstore.com</p>
        <p>Phone: +90 555 123 4567</p>
      </div>
    </div>
    <div class="footer-bottom">
      <p>&copy; 2025 All rights reserved.</p>
    </div>
  </footer>
</template>

<script>
export default {};
</script>

<style scoped>
.footer {
  background-color: #f2f2f2;
  padding: 20px;
  font-size: 14px;
  color: #555;
}
.footer-top {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  margin-bottom: 10px;
}
.social-icons {
  display: flex;
  gap: 15px;
}
.social-icons a {
  text-decoration: none;
  color: #007bff;
}
.social-icons a:hover {
  text-decoration: underline;
}
.contact-info {
  text-align: center;
}
.footer-bottom {
  text-align: center;
  font-size: 12px;
  color: #999;
  border-top: 1px solid #ddd;
  padding-top: 10px;
}
</style>
